### ISSUE TITLE
phobos2pyfa not currently working

### ISSUE THREAD

**Issue by blitzmann** [DarkFenX/pyfa-experimental#2]
Had a bit of a snag when trying to get this to work:

    ....
    processing phbmetadata
    applying conversion: basic attributes relocation
    Traceback (most recent call last):
      File "C:/Users/Ryan/Copy/Git/blitzmann/Pyfa-experimental/scripts/phobos2pyfa.py", line 182, in <module>
        process_conversions(edb_session, json_path)
      File "C:/Users/Ryan/Copy/Git/blitzmann/Pyfa-experimental/scripts/phobos2pyfa.py", line 159, in process_conversions
        conversion(edb_session, json_path)
      File "C:/Users/Ryan/Copy/Git/blitzmann/Pyfa-experimental/scripts/phobos2pyfa.py", line 140, in move_basic_attribs
        attribute_value = row.get(invtypes_name)
    AttributeError: 'str' object has no attribute 'get'

It stems from this in `move_basic_attribs`:

    for row in load_table(json_path, 'invtypes'):
        for invtypes_name, attribute_id in basic_attributes.items():
            attribute_value = row.get(invtypes_name)

row in this case is a string of the item's ID, and not the dict of attributes as I assume it should be. So I change this to `for _, row in load_table(json_path, 'invtypes').items()`. But, when commiting the changes, I get a SQLite exception about NULL:

    Traceback (most recent call last):
      File "C:\Users\Ryan\Copy\WinPython-32bit-3.4.3.5\python-3.4.3\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
        context)
      File "C:\Users\Ryan\Copy\WinPython-32bit-3.4.3.5\python-3.4.3\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: invgroups.categoryID

Not knowing the backend well enough yet to determine if this should or shouldn't be null, not sure how to handle this.

**Comment by DarkFenX** [comment]
I have these issues 'quick-fixed' locally, but as i don't have time for proper fix - i haven't pushed anything yet.

**Comment by DarkFenX** [comment]
Works now
